#!/usr/bin/env python3

import sys
import snappylib.place as place
import snappylib.commands as commands
import snappylib.config as config

# XXX: should be in a config file
#place.Place("test", "/test")


if len(sys.argv) < 2:
    commands.usage.call()
else:
    sys.argv.pop(0)
    # Special case for the check command - it will want control over loading
    # the ini file itself
    if sys.argv[0] != "check":
        config.loadINI()
    commands.byname.get(sys.argv.pop(0), commands.usage).call()
